/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as BookedBookingIdRouteImport } from './routes/booked.$bookingId'
import { Route as VenueVenueIdRouteImport } from './routes/venue.$venueId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const BookedBookingIdRoute = BookedBookingIdRouteImport.update({
  id: '/booked/$bookingId',
  path: '/booked/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const VenueVenueIdRoute = VenueVenueIdRouteImport.update({
  id: '/venue/$venueId',
  path: '/venue/$venueId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/booked/$bookingId': typeof BookedBookingIdRoute
  '/venue/$venueId': typeof VenueVenueIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/booked/$bookingId': typeof BookedBookingIdRoute
  '/venue/$venueId': typeof VenueVenueIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/booked/$bookingId': typeof BookedBookingIdRoute
  '/venue/$venueId': typeof VenueVenueIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/account' | '/booked/$bookingId' | '/venue/$venueId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/account' | '/booked/$bookingId' | '/venue/$venueId'
  id: '__root__' | '/' | '/account' | '/booked/$bookingId' | '/venue/$venueId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  BookedBookingIdRoute: typeof BookedBookingIdRoute
  VenueVenueIdRoute: typeof VenueVenueIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booked/$bookingId': {
      id: '/booked/$bookingId'
      path: '/booked/$bookingId'
      fullPath: '/booked/$bookingId'
      preLoaderRoute: typeof BookedBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venue/$venueId': {
      id: '/venue/$venueId'
      path: '/venue/$venueId'
      fullPath: '/venue/$venueId'
      preLoaderRoute: typeof VenueVenueIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  BookedBookingIdRoute: BookedBookingIdRoute,
  VenueVenueIdRoute: VenueVenueIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
